# .yaml code: mandatory indentation

# it is triggered when pull request
name: Test (when pull request)

on:
  pull_request:
    branches: [master]

# steps to run (test deploy)
jobs:
  test:
    name: Test Deploy Job (pull request)
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10   # python --version on my machine

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.4.2  # terraform --version on my machine

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}   # define on github, settings, secrets and variables, actions menu
        aws-secret-access-Key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   # define on github, settings, secrets and variables, actions menu
        aws-region: us-east-2

    #- name: Build Lambda package
    #  run: |
    #    sh scripts/build_lambda_package.sh

    - name: IaC Apply (test)
      env:
        COMMAND_IAC: terraform
      run: |
        cd iac
        $COMMAND_IAC init
        $COMMAND_IAC validate
        $COMMAND_IAC plan